name: Prod Deploy Utility App
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 'Production'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify node version
      run: node --version

    - name: Install dependencies
      working-directory: ./quickshop-utility-app
      run: npm install

    - name: Use prod environment file
      run: cp ./quickshop-utility-app/.env.prod ./quickshop-utility-app/.env

    - name: Build
      working-directory: ./quickshop-utility-app
      run: npm run build

    - name: Use prod app links config file
      run: |
        mkdir -p ./quickshop-utility-app/out/.well-known  
        cp ./app-links/assetlinks-prod.json ./quickshop-utility-app/out/.well-known/assetlinks.json

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebaseServiceAccount: '${{ secrets.FB_HOSTING_CREDENTIALS }}'
        channelId: live
        projectId: quickshop-prod